#version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/Users
      - JWT_SECRET=you_secret_key
    command: npm run start
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    container_name: mongodb
    image: mongo:5.0
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
